<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Codec/Protobuf/Packet.proto

namespace Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>common.Packet</code>
 */
class Packet extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 kind = 1;</code>
     */
    private $kind = 0;
    /**
     * <code>bytes data = 2;</code>
     */
    private $data = '';

    public function __construct() {
        \GPBMetadata\Codec\Protobuf\Packet::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 kind = 1;</code>
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * <code>int32 kind = 1;</code>
     */
    public function setKind($var)
    {
        GPBUtil::checkInt32($var);
        $this->kind = $var;
    }

    /**
     * <code>bytes data = 2;</code>
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * <code>bytes data = 2;</code>
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;
    }

}

