<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Codec/Protobuf/Packet.proto

namespace GPBMetadata\Codec\Protobuf;

class Packet
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a530a1b436f6465632f50726f746f6275662f5061636b65742e70726f74" .
            "6f1206636f6d6d6f6e22240a065061636b6574120c0a046b696e64180120" .
            "012805120c0a046461746118022001280c620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

